### ISSUE TITLE
Can nativeaot be supported

### ISSUE THREAD

**Issue by williamlzw** [jchristn/WatsonWebserver#107]
![Q2E 6K V~@DQ{`AHX0_ 9@E](https://user-images.githubusercontent.com/11348670/226790300-36e633e5-0539-458c-976a-0ffe11014262.png)

**Comment by jchristn** [comment]
Please clone the source and make the suggested change discussed on the issue you filed for HttpServerLite: https://github.com/jchristn/HttpServerLite/issues/26

**Comment by jchristn** [comment]
So it looks like ```nativeaot``` cannot be supported in the code as it exists currently.  ```Assembly.GetCallingAssembly()``` is required in order to load routes from the code using the library.  There could certainly be a version of the server that doesn't support static routes, parameter routes, and dynamic routes, however, I don't know if removing those capabilities would necessary mean the library directly supports ```nativeaot```.  If you would like to test and let me know, please do.

**Comment by williamlzw** [comment]
In the near future,. NET 8.0 may support nativeaot compilation reflection methods.
