### ISSUE TITLE
Use SSL cert in code

### ISSUE THREAD

**Issue by absid89** [jchristn/WatsonWebserver#13]
Hi! Thanks a lot for WatsonWebServer, it save my project on WinForms. Do you have plans to add support for using a certificate in code? It would be very convenient to use the server instead of the netsh commands.

**Comment by absid89** [comment]
I apologize in advance if I have asked for too much. I have no idea how long it will take to add such a function to the code.

**Comment by jchristn** [comment]
Hi @absid89 thank you for your request!  You have not asked for too much at all.  I'd love to add SSL support into the code itself.  The challenge I face is that to do so requires 1) wrapping the ```netsh``` commands into a method using ```Process.Start``` and then 2) interact with the certificate store to ensure the certificate is available.  

The main reason I haven't done this is because the process is different on both Windows and Linux, and I had hoped to keep Watson cross-platform.  The second reason is that handling all of the failure cases for both items above is pretty challenging.  That's why I opted to document using Watson with SSL rather than trying to bring these capabilities into the code.

Hope this makes sense.  Thanks

**Comment by absid89** [comment]
I now understand, thanks for the answer, the issue can be closed
