### ISSUE TITLE
Web server stops immediately after await StartAsync()

### ISSUE THREAD

**Issue by knaepel** [jchristn/WatsonWebserver#57]
Hi,

I think there is a bug in the new 4.x Major release. Where are coming from 3.x. If I call await server.StartAsync() the server stops immediately. 

The bug might be this [line](https://github.com/jchristn/WatsonWebserver/blob/e9f2c388842fbcac7a4d44da07cbb29458fc93e7/WatsonWebserver/WatsonWebserver.cs#L201).

~~~c#
return Task.Delay(1);
~~~

Should it not be so?

~~~c#
return Task.Delay(-1)
~~~

**Comment by jchristn** [comment]
Hi @knaepel I wanted the method to return control after the ```AcceptConnections``` method was started rather than returning the ```AcceptConnections``` task itself.  That way, if your ```await server.StartAsync``` had code following, it could continue.  

I just tested on my side and the server remains running after ```await server.StartAsync``` returns.  

Can you reproduce the behavior with the ```Test.Default``` project?  Which OS are you using and which runtime?

**Comment by knaepel** [comment]
Hi @jchristn, thanks for the answer. You are right, the server continues run after the 'await server.StartAsync()'. We just added our own Task.Delay(-1) so that the console application doesn't terminate.

**Comment by jchristn** [comment]
Awesome @knaepel - have a good one!
